### PR TITLE
fix readme and save the content to file

### PR DESCRIPTION
**Pull request by aaronlin**
I have fixed the error in README so that users can run the program successfully, and I also change from printing the crawled content to save to the files. Since I am not familiar with Scrapy, please let me know if anything changes would make this fix better. thanks

### CODE REVIEW

**Comment by afunTW** [comment]
@aaronlin Sorry for the late reply.

It's fine to fix the path, but you replace yield data is not right.
What the scrapy do is handling the saving process in `pipeline.py`.
Printing the crawled data is its debug message.

**Comment by aaronlin** [comment]
@afunTW Thanks for your suggestion. I have reverted the code back and also test it and find another bug. please take a look. thanks

**Comment by aaronlin** [comment]
I also fix that when the article is removed, the spider will fail in binary search

**Review by afunTW — COMMENTED** [review]
update: README fixed typo
- command line argument is `pages` in spider

bugfixed: pipeline should determinate the pages by `spider.pages`

bugfixed: check the link to avoid the removed article

**Pull request merged**
